# Generated by Django 4.2.8 on 2023-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='correctAnswer',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='options',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='question',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
